### ISSUE TITLE
character spam in chat when clicking on villager

### ISSUE THREAD

**Issue by Westloch** [Xyaafol/VilllagerModifications#3] opened 2020-07-04 00:27 UTC
just updated to version 1.3.3 and every time anyone clicks on a villager it spams the number **0**.

it spams the number 0 depending on how many trades that villager has, for example if the villager only has 2 trades avasilable itll print in chat two "**0**", if the villager has 6 trades available itll print six "**0**" in chat
![image](https://user-images.githubusercontent.com/62856212/86501927-2ea1f780-bd63-11ea-936f-458a1f2be959.png)

**Comment by Westloch** [comment] 2020-07-04 03:06
downgraded to v1.3.2 and issue went away. The problem seems to be with v1.3.3

**Comment by Xyaafol** [comment] 2020-07-04 06:09
I apologise for this issue - caused by my forgetful self leaving in a line of code when I was testing. This is now fixed in the newest version 1.3.4 on spigot. :)

**Closed as completed by Xyaafol** 2020-07-04 06:09 UTC
